name: CMLOps1
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli=1.0.9=he6710b0_2
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py39h06a4308_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.6.0=py39hef51801_0
  - ipython=7.30.1=py39hf3d152e_0
  - jedi=0.18.1=py39hf3d152e_0
  - jpeg=9d=h7f8727e_0
  - jupyter_client=7.1.0=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py39hf3d152e_1
  - kiwisolver=1.3.1=py39h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.5.0=py39h06a4308_0
  - matplotlib-base=3.5.0=py39h3ed280b_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1l=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py39h5aabda8_0
  - pip=21.2.4=py39h06a4308_0
  - prompt-toolkit=3.0.24=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pygments=2.11.1=pyhd8ed1ab_0
  - pyqt=5.9.2=py39h2531618_6
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.1=py3.9_cuda10.2_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - pyzmq=19.0.2=py39hb69f2a1_2
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py39h06a4308_0
  - sip=4.19.13=py39h2531618_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.37.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.10.1=py39_cu102
  - torchvision=0.11.2=py39_cu102
  - tornado=6.1=py39h3811e60_1
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021e=hda174b7_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiohttp-retry==2.4.6
    - aiosignal==1.2.0
    - alabaster==0.7.12
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.1
    - async-timeout==4.0.2
    - asyncssh==2.8.1
    - atpublic==2.3
    - attrs==21.4.0
    - awscli==1.22.28
    - babel==2.9.1
    - binaryornot==0.4.4
    - black==21.12b0
    - bleach==4.1.0
    - botocore==1.23.28
    - cachetools==4.2.4
    - cffi==1.15.0
    - cfgv==3.3.1
    - chardet==4.0.0
    - charset-normalizer==2.0.9
    - click==8.0.3
    - colorama==0.4.3
    - commonmark==0.9.1
    - configobj==5.0.6
    - configparser==5.2.0
    - cookiecutter==1.7.3
    - coverage==6.2
    - cryptography==36.0.1
    - defusedxml==0.7.1
    - dictdiffer==0.9.0
    - diskcache==5.4.0
    - distlib==0.3.4
    - distro==1.6.0
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - docutils==0.15.2
    - dpath==2.0.5
    - dulwich==0.20.26
    - dvc==2.9.3
    - filelock==3.4.2
    - flake8==4.0.1
    - flatten-dict==0.4.2
    - flufl-lock==6.0
    - frozenlist==1.2.0
    - fsspec==2021.11.1
    - ftfy==6.0.3
    - funcy==1.17
    - future==0.18.2
    - gcsfs==2021.11.1
    - gitdb==4.0.9
    - gitpython==3.1.24
    - google-api-core==2.3.2
    - google-api-python-client==2.34.0
    - google-auth==2.3.3
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.4.6
    - google-cloud-core==2.2.1
    - google-cloud-storage==1.44.0
    - google-crc32c==1.3.0
    - google-resumable-media==2.1.0
    - googleapis-common-protos==1.54.0
    - grandalf==0.6
    - grpcio==1.43.0
    - httplib2==0.20.2
    - hydra-core==1.1.1
    - identify==2.4.4
    - idna==3.3
    - imagesize==1.3.0
    - importlib-metadata==4.10.0
    - iniconfig==1.1.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - isort==5.10.1
    - jinja2==3.0.3
    - jinja2-time==0.2.0
    - jmespath==0.10.0
    - joblib==1.1.0
    - jsonschema==4.3.3
    - jupyter==1.0.0
    - jupyter-console==6.4.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - kornia==0.6.2
    - mailchecker==4.1.7
    - markdown==3.3.6
    - markupsafe==2.0.1
    - mccabe==0.6.1
    - mistune==0.8.4
    - multidict==5.2.0
    - mypy==0.930
    - mypy-extensions==0.4.3
    - nanotime==0.5.2
    - nbclient==0.5.9
    - nbconvert==6.3.0
    - nbformat==5.1.3
    - networkx==2.6.3
    - nodeenv==1.6.0
    - notebook==6.4.6
    - oauth2client==4.1.3
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - opencv-python==4.5.5.62
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - pathspec==0.9.0
    - pathtools==0.1.2
    - phonenumbers==8.12.40
    - pipreqs==0.4.11
    - platformdirs==2.4.1
    - pluggy==1.0.0
    - ply==3.11
    - poyo==0.5.0
    - pre-commit==2.16.0
    - prometheus-client==0.12.0
    - promise==2.3
    - protobuf==3.19.1
    - psutil==5.9.0
    - py==1.11.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.8.0
    - pycparser==2.21
    - pydot==1.4.2
    - pydrive2==1.10.0
    - pyflakes==2.4.0
    - pygit2==1.7.2
    - pygtrie==2.4.2
    - pyopenssl==21.0.0
    - pyparsing==3.0.6
    - pyrsistent==0.18.0
    - pytest==6.2.5
    - python-benedict==0.24.3
    - python-dotenv==0.19.2
    - python-fsutil==0.5.0
    - python-slugify==5.0.2
    - pytz==2021.3
    - pyyaml==5.4.1
    - qtconsole==5.2.2
    - qtpy==2.0.0
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rich==10.16.2
    - rsa==4.7.2
    - ruamel-yaml==0.17.20
    - ruamel-yaml-clib==0.2.6
    - s3transfer==0.5.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - scmrepo==0.0.7
    - send2trash==1.8.0
    - sentry-sdk==1.5.1
    - shortuuid==1.0.8
    - shtab==1.5.3
    - sklearn==0.0
    - smmap==5.0.0
    - snakeviz==2.1.1
    - snowballstemmer==2.2.0
    - sphinx==4.3.2
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - subprocess32==3.5.4
    - tabulate==0.8.9
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.5.0
    - text-unidecode==1.3
    - threadpoolctl==3.0.0
    - toml==0.10.2
    - tomli==1.2.3
    - torch-tb-profiler==0.3.1
    - tqdm==4.62.3
    - uritemplate==4.1.1
    - urllib3==1.26.7
    - virtualenv==20.13.0
    - voluptuous==0.12.2
    - wandb==0.12.9
    - webencodings==0.5.1
    - werkzeug==2.0.2
    - wget==3.2
    - widgetsnbextension==3.5.2
    - xmltodict==0.12.0
    - yarg==0.1.9
    - yarl==1.7.2
    - yaspin==2.1.0
    - zc-lockfile==2.0
    - zipp==3.7.0
prefix: /home/slangen/anaconda3/envs/CMLOps1
