wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 32
BEST_MODEL_PATH:
  desc: null
  value: models/checkpoints/best_model.pth
BEST_VAL:
  desc: null
  value: 100000000
CHECKPOINT_PATH:
  desc: null
  value: models/checkpoints/
DROPOUT_PROBABILITY:
  desc: null
  value: 0.2
EPOCHS:
  desc: null
  value: 10
LEARNING_RATE:
  desc: null
  value: 0.0001
N_WORKERS:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1642411154
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 16
      4: 3.9.7
      5: 0.12.9
      8:
      - 5
