DATA:
URL: "https://data.mendeley.com/public-files/datasets/jctsfj2sfn/files/148dd4e7-636b-404b-8a3c-6938158bc2c0/file_downloaded"
FILENAME: "covid19-pneumonia-normal-chest-xraypa-dataset.zip"
FOLDERNAME: "COVID19_Pneumonia_Normal_Chest_Xray_PA_Dataset"
CHUNK_SIZE: 1024

PREPROCESS:
PLOT_SAMPLE: False,
OUTPUT_FILEPATH: "data/preprocessed/covid_not_norm/"
MAX_PER_CLASS: 10000

OTHERS:
FIG_PATH: "reports/figures"
RAW_DATA: "data/raw/COVID19_Pneumonia_Normal_Chest_Xray_PA_Dataset"
VALIDATION_SPLIT: 0.4
SEED: 42
